[package]
name = "piecrust"
version = "0.1.0"
edition = "2021"

[dependencies]
piecrust-uplink = { path = "../piecrust-uplink" }

wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "b501c166" }
wasmer-vm = { git = "https://github.com/wasmerio/wasmer", rev = "b501c166" }
wasmer-types = { git = "https://github.com/wasmerio/wasmer", rev = "b501c166" }
wasmer-middlewares = { git = "https://github.com/wasmerio/wasmer", rev = "b501c166" }
wasmer-compiler-singlepass = { git = "https://github.com/wasmerio/wasmer", rev = "b501c166" }
bytecheck = "0.6"
rkyv = { version = "0.7", features = ["size_32", "validation"] }
parking_lot = "0.12"
blake3 = "1"
colored = "2"
libc = { version = "^0.2", default-features = false }
region = "3"
tempfile = "3"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "stack"
harness = false
