[package]
name = "piecrust-uplink"
description = """
Build smart contracts directly on top of Dusk's `piecrust` virtual machine.\
"""
categories = ["wasm", "no-std", "cryptography::cryptocurrencies"]
keywords = ["virtual", "machine", "smart", "contract", "wasm"]

repository = "https://github.com/dusk-network/piecrust"
version = "0.2.0"

edition = "2021"
license = "MPL-2.0"

[dependencies]
rkyv = { version = "0.7", default-features = false, features = ["size_32", "alloc"] }
bytecheck = { version = "0.6", default-features = false }
wee_alloc = { version = "0.4", optional = true }

[features]
default = ["std"]
std = []
