[package]
name = "constructor"
version = "0.1.0"
authors = [
    "Milosz Muszynski <milosz@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
piecrust-uplink = { path = "../../piecrust-uplink", default-features = false, features = ["wee_alloc"] }

[lib]
crate-type = ["cdylib", "rlib"]
